### ISSUE TITLE
locus relations: Changing the type of an existing relation drops file identifier cache instead of changing it

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1278]
I have an existing relation with an image. Looks like this in the gallery:
![image](https://user-images.githubusercontent.com/38838314/146995391-300d9ef5-84ff-416f-b474-ad0c3e318d47.png)
When changing the type to something else, the image stays in the gallery but "LA Test-003" and "LA Test-002" are gone from the gallery.

What should happen is that the image's primary text changes. You find that one in the gallery by clicking on the popup-button:
![image](https://user-images.githubusercontent.com/38838314/146995561-08124c74-09e3-4461-b268-36506ee33415.png)

The "La test-003is abutted by LA test-002" label should change to whatever would be expected when changing the type.

**Comment by urapadmin** [comment]
### @test 11.6.15
- [ ] this should work now after I have updated that image container to the latest image container technique. It should be tested together with #1250

**Comment by luizaogs** [comment]
I just tried to change a relation to see if this was working despite the error 1 just reported in #1250 but when I did I got a flashing screen of the code (the same that's visible in the screen interruption issue). The screen went away by itself and the relation appears properly in the relations module, but the identifiers are gone from the image in the gallery still.

**Comment by urapadmin** [comment]
what exactly did you change? The type?

**Comment by urapadmin** [comment]
### 11.6.16
I see the flashing screen with the record table as well and there is not much I can do about it without upending half of the code here. I can live with that part.

> The screen went away by itself and the relation appears properly in the relations module, but the identifiers are gone from the image in the gallery still.
- [ ] That part should definitely not happen. BUT it might be good now in 11.6.16 because of #1250.

**Comment by mcornacchia25** [comment]
This seems to be working now. I also get the flash of the code, but the changed relation label shows up correctly in the gallery.

**Comment by luizaogs** [comment]
Hmm, I'm still having the same issue. I just changed the type of the relation and now the image lacks identifiers (it had the proper ones before). The identifiers are also lost in the gallery if I change the locus of the relation rather than the type. This is in 11.6.16.

**Comment by mcornacchia25** [comment]
Strange. If I only have one relation, it changes it properly, but if I add a second, that one has this error when changing its type. I can still change the type of the first one with no issue.

**Comment by luizaogs** [comment]
Yep that's totally true, I was testing in a list. Changing the type works for the first relation in a list, not the ones above. But I just tried changing the locus of the first relation in the list and I don't lose the identifiers in the gallery, but they do not update so there is a mismatch between locus and description: 

![IMG_7451F0E0CFCD-1](https://user-images.githubusercontent.com/67970402/147298664-ae4c4a10-c5b7-401a-9088-0333a84b05fc.jpeg)

LA test-006 is the locus the relation was changed to, so the description was updated but the identifier was not (it stayed as LA test-003).

**Comment by urapadmin** [comment]
very promising testing collaboration, I must say! This will help me to reproduce and then battle the issue.

**Comment by urapadmin** [comment]
ignore this one in 11.6.17. I have to unravel it all.

**Comment by urapadmin** [comment]
### @test 11.6.23
This needs an entirely new test, 
- including the image container, 
- making sure that the opposite relation is correctly updated
- checking on the image's descriptions in the gallery (e.g. if A cuts through B, B is cut by A should be listed in the image's info in the gallery)

manipulating the image container itself leads to a delayed flicker while manipulating the type or the locus leads to a somewhat different flicker that is not delayed. In both cases we should see only one flicker.

**Comment by urapadmin** [comment]
by the way, not all of you need to test this systematically in depth, one would do. But everybody should poke around and try a few things with the container and the type etc.

**Comment by lbestock** [comment]
First buglet. I created two new contexts. I then created a locus relationship in the second one, and defined it as "adjacent to". When I then went to choose the context to which the relationship applied (the first of the new contexts) I got here: 
![image](https://user-images.githubusercontent.com/49291909/151678743-39f5ffe2-703e-48ee-b1c9-b8c727d61c82.png)
FM Go is not letting me close it properly, either.

**Comment by urapadmin** [comment]
ja, 11.6.23b on its way ....

**Comment by urapadmin** [comment]
### 11.6.23b
addresses the problem @lbestock ran into. It happened when creating a new relationsship and add type and related locus first BEFORE adding an image.

**Comment by lbestock** [comment]
I have now tested this with first, second, and third relations. They were all working. 
I have also done a systematic image container test with locus relations. Aside from the fact that the popup only allows inserting from the gallery, not using the camera or signature tool as is possible in other image containers, everything worked as I expected. That might be a popup in a popup issue again like ceramics? Anyway, Lutz I won't close it. You can close it if you find my test sufficient, or you can wait until @mcornacchia25 and @luizaogs poke around a little bit. This one seems too big to close so quickly!

**Comment by luizaogs** [comment]
Argh. I just got a 1 when adding the image to the second relation in a list...

**Comment by luizaogs** [comment]
Also, when manipulating the type or locus of the relation the flicker takes a while and the screen with the code is visible so I wonder if inserting a "please wait" panel would help but this is picky and less important than the horrible 1 reported above.

**Comment by urapadmin** [comment]
### 11.6.23c
I have improved - hopefully - the flickering windows in locus relations. It should be faster now and less scary. 
I have no words for your one, Luiza. No words.

**Comment by urapadmin** [comment]
@luizaogs: 
- what are your current versions?
- how many other apps do you have open?
- once you got it in locus relations, do you get it anywhere else?

**Comment by luizaogs** [comment]
ok, still in 11.6.23b, iOS 15.2.1, FM 19.4.2.202

When I first got it the app store might have been open and files and Safari certainly were. Now I only have FM Go open but am still getting it. 

I just tried adding two images to all other image container types and did not get 1s, so at least it seems like the issue is unique to locus relations.

When I get it in locus relations it is when I add the image to the primary container, yes.

**Comment by luizaogs** [comment]
Shall I try 11.6.23c?

**Comment by urapadmin** [comment]
I am about to make you a 11.6.23d in a jiffy

**Comment by urapadmin** [comment]
there you go:
### 11.6.23d
the difference here is that the locus relations image container so far used a .2 second delay and now uses the same delay all other image containers use, too. By the way it is controlled by a config setting under "admin": "delay_cache_operation_msec"

**Comment by urapadmin** [comment]
😡

**Comment by luizaogs** [comment]
Sorry for always being the one to mess up image containers, angry spider :)

But you'll be happy to hear that I just added a zillion relations (one for each type) and got no 1s. So, resolved? I say cautiously optimistically.

**Comment by luizaogs** [comment]
Oh and the flickers are definitely less scary now.

**Comment by urapadmin** [comment]
this is not software engineering. This is try and error.

**Comment by urapadmin** [comment]
okay, we wait for @mcornacchia25 here and if she can't generate any horrors with 11.6.23d, we just close this.

**Comment by mcornacchia25** [comment]
Oh no. I created a relation, which worked as expected (context 1 labelled below, context 2 labelled above). Then I changed the relationship on 2 to below. I then went to the image gallery where there were 3 relations on the image. 2 is labelled correctly as below, but 1 is labelled both above and below.

![IMG_18564A1B9BC5-1](https://user-images.githubusercontent.com/96021337/151714507-9cfeb158-03a5-4af6-a427-b1d1daf9698b.jpeg)

**Comment by urapadmin** [comment]
can you please upload that database to your workstation?

**Comment by mcornacchia25** [comment]
Done

**Comment by urapadmin** [comment]
you are so fast 😲. Thanks.

**Comment by urapadmin** [comment]
good. I can reproduce this. There's hope.

**Comment by urapadmin** [comment]
ja, this simply still does not work. Inserting an image in the second locus relation creates a correct description for the connection between the current and the related locus but not in the other direction. The relation between the other locus and this one has no description.

![image](https://user-images.githubusercontent.com/38838314/151728262-7e2ec7a0-f087-434f-8734-6d1a1ead4ddf.png)

**Comment by urapadmin** [comment]
> Oh no. I created a relation, which worked as expected (context 1 labelled below, context 2 labelled above). Then I changed the relationship on 2 to below. I then went to the image gallery where there were 3 relations on the image. 2 is labelled correctly as below, but 1 is labelled both above and below.
> 
> ![IMG_18564A1B9BC5-1](https://user-images.githubusercontent.com/96021337/151714507-9cfeb158-03a5-4af6-a427-b1d1daf9698b.jpeg)
> 
> Also happened with cut by / cuts through
we follow this one up in #1330

**Comment by urapadmin** [comment]
### @test: 11.6.24
🐛  got him. This should be fixed

**Comment by luizaogs** [comment]
Did a systematic test and tried everything (changing type of relation and loci, as well as deletions) with first, second, third, and fourth relations. I believe it's all working.

**Comment by mcornacchia25** [comment]
Did a quick test and everything seems to be working for me

**Comment by urapadmin** [comment]
@lbestock: Now it is on you to let the next bug appear

**Comment by lbestock** [comment]
Hmpf it seems MCP is actually not up, not just giving a fake warning. So I won’t be able to close this for you before my zooms start.

**Comment by urapadmin** [comment]
it seems we need to practice restarting it. It is back up.

**Comment by lbestock** [comment]
Alrighty then, you asked :)
I made three relations. I checked that things were proper and was doing swimmingly. For fun, I decided to delete the second relation's image from within the gallery itself: I clicked on the popup, got the information tab for the image, where everything was as it should be, and then I hit the delete button. After confirming that I wanted to delete the record, things looked good - no more photo in gallery, and no more photo in the relationship but the relationship was still there. So I added another photo to the relationship without changing anything else (this is the relation CA-006 cut by CA-003). Looks proper in my image relations tab, but when I go to the gallery it was really funny! I have that image, with no apparent relations. And I have a blank image in the gallery for CA-006 CA-003. 
![IMG_0014](https://user-images.githubusercontent.com/49291909/151846105-a26d324f-eba3-4b63-9975-e5b953bfcc68.PNG)
![image](https://user-images.githubusercontent.com/49291909/151846203-54f3928f-97af-41df-a3e7-0b7f66baa96f.png)

**Comment by lbestock** [comment]
It does not appear to have anything to do with where something is in the list. I went to a different context and made just one relation, did the same thing with the images, and had the same result.

**Comment by lbestock** [comment]
You expected it and it’s not a problem, so I close this guy!

**Comment by urapadmin** [comment]
yes, just for the others: That delete button in the gallery is supposed to be used ONLY if you know that there is no remaining relation to that image. It is really a button for testing to clean up ones mess a bit.
